### ISSUE TITLE
when deployment hosted engine, step 5 : deploy vm failure

### ISSUE THREAD

**Issue by viktarbychko92** [oVirt/ovirt-ansible-collection#263] opened 2021-01-16 09:46 UTC
Log info:
```
2021-01-16 11:58:57,273+0300 ERROR ansible failed {
    "ansible_host": "localhost",
    "ansible_playbook": "/usr/share/ovirt-hosted-engine-setup/ansible/trigger_role.yml",
    "ansible_result": {
        "_ansible_no_log": false,
        "attempts": 180,
        "changed": true,
        "cmd": [
            "hosted-engine",
            "--vm-status",
            "--json"
        ],
        "delta": "0:00:00.169234",
        "end": "2021-01-16 11:58:56.882923",
        "invocation": {
            "module_args": {
                "_raw_params": "hosted-engine --vm-status --json",
                "_uses_shell": false,
                "argv": null,
                "chdir": null,
                "creates": null,
                "executable": null,
                "removes": null,
                "stdin": null,
                "stdin_add_newline": true,
                "strip_empty_ends": true,
                "warn": true
            }
        },
        "rc": 0,
        "start": "2021-01-16 11:58:56.713689",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "{\"1\": {\"host-id\": 1, \"host-ts\": 4262, \"score\": 3400, \"engine-status\": {\"vm\": \"up\", \"health\": \"bad\", \"detail\": \"Powering down\", \"reason\": \"failed liveliness check\"}, \"hostname\": \"okdh01.xby.icdc.io\", \"maintenance\": false, \"stopped\": false, \"crc32\": \"16e1340b\", \"conf_on_shared_storage\": true, \"local_conf_timestamp\": 4262, \"extra\": \"metadata_parse_version=1\\nmetadata_feature_version=1\\ntimestamp=4262 (Sat Jan 16 11:58:54 2021)\\nhost-id=1\\nscore=3400\\nvm_conf_refresh_time=4262 (Sat Jan 16 11:58:54 2021)\\nconf_on_shared_storage=True\\nmaintenance=False\\nstate=EngineStop\\nstopped=False\\ntimeout=Thu Jan  1 04:11:21 1970\\n\", \"live-data\": true}, \"global_maintenance\": false}",
        "stdout_lines": [
            "{\"1\": {\"host-id\": 1, \"host-ts\": 4262, \"score\": 3400, \"engine-status\": {\"vm\": \"up\", \"health\": \"bad\", \"detail\": \"Powering down\", \"reason\": \"failed liveliness check\"}, \"hostname\": \"okdh01.xby.icdc.io\", \"maintenance\": false, \"stopped\": false, \"crc32\": \"16e1340b\", \"conf_on_shared_storage\": true, \"local_conf_timestamp\": 4262, \"extra\": \"metadata_parse_version=1\\nmetadata_feature_version=1\\ntimestamp=4262 (Sat Jan 16 11:58:54 2021)\\nhost-id=1\\nscore=3400\\nvm_conf_refresh_time=4262 (Sat Jan 16 11:58:54 2021)\\nconf_on_shared_storage=True\\nmaintenance=False\\nstate=EngineStop\\nstopped=False\\ntimeout=Thu Jan  1 04:11:21 1970\\n\", \"live-data\": true}, \"global_maintenance\": false}"
        ]
    },
    "ansible_task": "Check engine VM health",
    "ansible_type": "task",
    "status": "FAILED",
    "task_duration": 976
}
```
The deployment environment: engine rpm version : ovirt-engine-appliance-4.4 、 OS : ovirt node 4.4.4

![Screenshot 2021-01-16 123742](https://user-images.githubusercontent.com/46712595/104808673-d7dca680-57f8-11eb-9782-deae9bd2dc2c.png)
![Screenshot 2021-01-16 123842](https://user-images.githubusercontent.com/46712595/104808675-d8753d00-57f8-11eb-859c-a24b3621e299.png)

**Comment by sandrobonazzola** [comment] 2022-02-17 10:04
@viktarbychko92 are you still able to reproduce with oVirt 4.4.10?

**Comment by arachmani** [comment] 2022-04-07 11:41
Since there were no recent updates on the matter, I'm closing it.
Feel free to re-open if required.

**Closed by arachmani** 2022-04-07 11:41 UTC
Labels: bug
