### ISSUE TITLE
cloud_init does not set the hostname of password for newly deployed VM

### ISSUE THREAD

**Issue by eddy-resnick** [oVirt/ovirt-ansible-collection#48] opened 2020-05-27 09:00 UTC
Using the ovirt_vm module and the cloud_init parameter to set hostname and root password has no effect on newly created VM from template.
Using Ansible 2.7.18 with the python-ovirt-engine-sdk4-4.3.2-1.el7ev.x86_64 installed.
deploy_vm.yml and role deploy_vm is attached
[ovirt_vm-cloud_init.zip](https://github.com/oVirt/ovirt-ansible-collection/files/4687672/ovirt_vm-cloud_init.zip)

**Comment by mnecas** [comment] 2020-05-27 13:41
Thanks for the report will look into it.

**Comment by mnecas** [comment] 2020-06-02 09:10
Hi,
checked your role and everything looked fine. 
But I was not able to reproduce on (have tried on 2.7.9 and 2.7 latest)
After running the playbook it added the host_name password etc. to the VM even that it was created from a template.
I will leave the issue open and try to look into it once again later. 


my task: 
``` yaml
    - ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: test4
        template: test12
        cluster: Default
        cloud_init_persist: True
        cloud_init:
          host_name: "test"
          root_password: "test"
          custom_script: |
            write_files:
             - content: |
                 Hello, world!
               path: /tmp/greeting.txt
               permissions: '0644'
```

**Comment by eddy-resnick** [comment] 2020-06-02 09:22
Martin.
Thanks for checking this out.
Can you please instruct me on how I access the newer versions?
Sincerely.
Eddy Resnick

**Comment by mnecas** [comment] 2020-06-08 07:21
The issue was resolved by adding cloud-init package to the template.

**Closed by mnecas** 2020-06-08 07:21 UTC
