### ISSUE TITLE
Rename collection?

### ISSUE THREAD

**Issue by gundalow** [oVirt/ovirt-ansible-collection#14] opened 2020-03-24 20:47 UTC
Is there a name the collection is called `ovirt.ovirt_collection` rather than something shorter?

As a reminder the collection name doesn't need to match the GitHub repo name

**Comment by mnecas** [comment] 2020-03-24 21:07
Is there some kind of standard for naming the collections?
If there is no particular reason why we should change it I would keep it because we already released it to the galaxy.

WDYT @mwperina

**Comment by mwperina** [comment] 2020-03-25 16:33
Well, we thought about it, but `ovirt.ovirt` doesn't make sense at all and just `ovirt` cannot be used.

I've looked at names of other collection names and there is often used `.cloud` suffix (openstack, google, ...), so maybe `ovirt.cloud` would be better, what do you think? Are there any best practices around collection naming, John?

@gundalow

**Comment by mnecas** [comment] 2020-03-26 17:07
I'm not sure how it will be in automation hub if we will have collection under some different namespace than the name `ovirt.ovirt` would not be worst.
Do you have some information about the automation hub @gundalow ?

**Comment by abenokraitis** [comment] 2020-03-30 15:45
`ovirt.ovirt` would be consistent with other naming of upstream collections, and would be simpler than putting the word `collection` in there, since that's redundant (project_name.collection_name.asset). The downstream Red Hat supported collection in Automation hub can have the same collection name but must be part of the `redhat.*` namespace.

**Comment by mnecas** [comment] 2020-03-30 20:25
Got two questions:
- If we rename the collection can we somehow remove the old collection from the galaxy or if we could update somehow the existing name?
- When we will use namespace redhat we will need to adapt whole collection to it?

**Comment by anshulbehl** [comment] 2020-03-31 16:25
@mnecas for the answer to first question:
You cannot remove or update the existing name of a collection, they will be uploaded as new collection. The only option is either to 
- Deprecate the old collection and upload the new one as `ovirt.ovirt`
- You can create the new collection and keep the old one as well, but the new version of old collection can be empty and will only have new one as a dependency which means whenever a user install the old one, new one will come with it.


for the answer to your second question:
Relative imports works inside collections, so you can do away with absolute imports that you have used like below (example)
`ansible_collections.ovirt.ovirt_collection.plugins.module_utils.ovirt import check_sdk`

and replace it with
`from ..module_utils.ovirt import check_sdk`

This way you can avoid namespace collisions  in your src when maintaining for two namespaces.
However, keep in mind that relative imports don't work for doc_fragments and you will have to change then with namespace.
That should be pretty minimal and what I would suggest is either you can do some sort of processing just before creating the collection tarball, or you can create a dependent collection that will house only the doc_fragments, and collection at AH and Galaxy will both depend on the same.

Let me know if this helps!!

**Comment by mnecas** [comment] 2020-03-31 18:04
@anshulbehl thanks for your info!

Around the first note:
I was expecting that we can only deprecate, but still wanted to ask. 
Great tip with linking the deprecated collection to the new one.

And second: 
I'll update the paths.
And the processing before creating tarball would make sense, but still would be better if the doc_fragments would work with relative paths.
We are right now doing something similar in build.sh, so for us it would be just adding the implementation to the build, but for other devs might not be so easy.
Do you think we should create an issue around it? Or do you think that this kind of feature would never work? Or is it by design?

**Comment by anshulbehl** [comment] 2020-03-31 18:43
I think it is by design from the conversations I have heard till today, @sivel Can you shed some more light on this?
Essentially, you should be the owner of the namespace on galaxy and hence that blocks other devs from uploading a patentially "bad" collection to your namespace and for people to adhere to process you can add specific items in contributing guidelines on the source repo.

Thanks,

**Comment by mnecas** [comment] 2020-03-31 19:25
I meant it would be good to resolve this issue for other developers who will write their own collection which will have an upstream and downstream release with a different namespace.

**Comment by anshulbehl** [comment] 2020-03-31 20:26
Generally that is not the case with any Ansible Partners, but with internal RH teams we would see such an issue.

**Comment by mnecas** [comment] 2020-04-01 07:53
Let's say that we rename the upstream to `ovirt.ovirt` that would be pretty straight forward, but we would have issues with the downstream `redhat.rhv`.
Right now I designed this collection so it does not have our roles [1]. All roles will require the collection with modules and implementation would be done in tasks. Reason for it was backward compatibility, so users who already have implemented our role does not need to import this. 
The issues with downstream would be
- put all our roles to this collection which would break the backward compatibility and would create a large unmanageable project.
- or use it separately. We would need to automatically update all roles depending on where it will go.

From my point of view, the best solution would be in downstream create symlinks to upstream so a user can use `redhat.rhv` and `ovirt.ovirt`. We would not need to do large changes, but would require the option in automation hub and also only if the `doc_fragments` could work with both versions simultaneously.

[1] https://github.com/ovirt/ovirt-ansible (you can find a list of all our roles)

**Comment by gundalow** [comment] 2020-04-07 12:07
Once confirmed we must review (and if needed) update https://github.com/ansible/ansible/pull/68448

**Comment by mnecas** [comment] 2020-04-07 14:56
I have added PR as you requested to rename the collection, but want to keep this issue open for further discussion around a downstream release.

**Comment by anshulbehl** [comment] 2020-04-07 15:03
@mnecas I would recommend maintaining two separate codebases for upstream and downstream. Although it doesn't look like it today but the downstream ansible project is going to diverge from upstream and you would have to maintain two versions for upstream and downstream eventually or put a lot of logic on top of one codebase to convert.

The symlinking should be avoided as support and certification policy would not permit any linkage to upstream content as well in downstream Automation Hub project.

**Comment by abenokraitis** [comment] 2020-05-07 02:43
@mnecas any updates here?

**Comment by mnecas** [comment] 2020-05-09 12:36
I talked with @mwperina and if we will decide to use the automation hub we will use need the namespace `ovirt`.
We will prepare some questions about the automation hub.

**Comment by abenokraitis** [comment] 2020-05-15 14:01
Looks like this happened? I see an `ovirt.ovirt` collection on Galaxy.

**Comment by mnecas** [comment] 2020-05-19 07:06
Yeah, I have renamed it as soon as I got a green light in #16. So new users don't need to change it. 
Around Automation Hub we will prepare an email.

**Closed by mnecas** 2020-05-19 07:06 UTC
