### ISSUE TITLE
ovirt_nic_info returns no description in ovirt44..

### ISSUE THREAD

**Issue by ThomasADavis** [oVirt/ovirt-ansible-collection#133] opened 2020-10-03 00:50 UTC
##### SUMMARY

I am working on upgrading to ovirt4.4 from a ovirt4.2 instance.

ovirt_nic_info returns a description dict, with values on ovirt4.2.  The same dict is empty on ovirt4.4

##### COMPONENT NAME

ovirt_nic_info

##### STEPS TO REPRODUCE

```
#
# Tst ovirt
#
- hosts:
    - localhost

  connection: local
  gather_facts: false

  tasks:
    - name: get the ovirt credentials from 1password.
      set_fact:
        engine_user: '{{ lookup( "onepassword", "ovirt44.omni", field="username" ) }}'
        engine_password: '{{ lookup( "onepassword", "ovirt44.omni", field="password" ) }}'
        engine_url: 'https://ovirt44.omni/ovirt-engine/api'

    - name: Login to oVirt
      ovirt_auth:
        url: https://ovirt44.omni/ovirt-engine/api
        username: "{{ engine_user }}@LDAP"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"

    - name: dump ovirt nic info from ovirt44
      ovirt_nic_info:
        auth: "{{ ovirt_auth }}"
        vm: "gryphon"
      register: ovirt44_nics

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      delegate_to: localhost
      run_once: true

    - set_fact:
        engine_password: '{{ lookup( "onepassword", "nim.nersc.gov", field="password" ) }}'
        engine_user: '{{ lookup( "onepassword", "nim.nersc.gov", field="username" ) }}'

    - name: Login to oVirt
      ovirt_auth:
        url: https://192.168.85.24/ovirt-engine/api
        username: "{{ engine_user }}@LDAP"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"

    - name: dump ovirt nic info from ovirt44
      ovirt_nic_info:
        auth: "{{ ovirt_auth }}"
        vm: "gryphon"
      register: ovirt42_nics

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      delegate_to: localhost
      run_once: true

    - name: dump ovirt44_nics
      debug:
        msg: "{{ ovirt44_nics }}"

    - name: dump ovirt42_nics
      debug:
        msg: "{{ ovirt42_nics }}"

```

##### EXPECTED RESULTS

This is from the ovirt4.2 system

```
           {
                "href": "/ovirt-engine/api/vms/85f6907d-4f9b-451c-88bc-6c9abfcccda5/nics/17b8a2ac-e983-4a15-a65a-b9fc3e634191",
                "id": "17b8a2ac-e983-4a15-a65a-b9fc3e634191",
                "interface": "virtio",
                "linked": true,
                "mac": {
                    "address": "00:1a:4a:16:01:3c"
                },
                "name": "onewire",
                "network_filter_parameters": [],
                "plugged": true,
                "reported_devices": [
                    {
                        "description": "guest reported data",
                        "href": "/ovirt-engine/api/vms/85f6907d-4f9b-451c-88bc-6c9abfcccda5/reporteddevices/6f6e6577-6972-6530-303a-31613a34613a",
                        "id": "6f6e6577-6972-6530-303a-31613a34613a",
                        "ips": [
                            {
                                "address": "192.168.93.254",
                                "version": "v4"
                            },
                            {
                                "address": "fe80::21a:4aff:fe16:13c",
                                "version": "v6"
                            }
                        ],
                        "mac": {
                            "address": "00:1a:4a:16:01:3c"
                        },
                        "name": "onewire",
                        "type": "network"
                    }
                ],
                "statistics": [],
                "vm": {
                    "href": "/ovirt-engine/api/vms/85f6907d-4f9b-451c-88bc-6c9abfcccda5",
                    "id": "85f6907d-4f9b-451c-88bc-6c9abfcccda5"
                },
                "vnic_profile": {
                    "href": "/ovirt-engine/api/vnicprofiles/00a6c245-529b-473a-b9fb-8cb2ea96166c",
                    "id": "00a6c245-529b-473a-b9fb-8cb2ea96166c"
                }
            }
        ]
```
##### ACTUAL RESULTS

This is from the ovirt4.4 system.  It does know the IP address and other information.

```
            {
                "href": "/ovirt-engine/api/vms/05064ce9-3be8-4410-b42b-d02325908b49/nics/4d4c91fa-93f2-4433-8a9c-bf7b42c4582d",
                "id": "4d4c91fa-93f2-4433-8a9c-bf7b42c4582d",
                "interface": "virtio",
                "linked": true,
                "mac": {
                    "address": "56:6f:e8:d6:00:2f"
                },
                "name": "pdunet",
                "network_filter_parameters": [],
                "plugged": true,
                "reported_devices": [],
                "statistics": [],
                "vm": {
                    "href": "/ovirt-engine/api/vms/05064ce9-3be8-4410-b42b-d02325908b49",
                    "id": "05064ce9-3be8-4410-b42b-d02325908b49"
                },
                "vnic_profile": {
                    "href": "/ovirt-engine/api/vnicprofiles/cb886599-a652-4006-b53e-2543747ebf3f",
                    "id": "cb886599-a652-4006-b53e-2543747ebf3f"
                }
            }

```

Is it possible to get any of the information that is in 4.2, from the 4.4 system?  I need to get the IPv4 addresses.

**Comment by mnecas** [comment] 2020-10-03 07:30
Hi @ThomasADavis,
thank you for opening this issue.
This is not a bug, the API probably had some changes, but you can work around it by using `fetch_nested` and `nested_attributes` parameters.
```yaml
    - name: dump ovirt nic info from ovirt44
      ovirt_nic_info:
        auth: "{{ ovirt_auth }}"
        vm: "gryphon"
        fetch_nested: True
        nested_attributes:
          - ips
          - description
          - mac
      register: ovirt42_nics
```

Please let me know if this resolves your issue.

**Comment by ThomasADavis** [comment] 2020-10-03 18:26
It does return the IP's now.

But I don't see this being documented in the ovirt_nic_info module.  Where is this documented at?

**Comment by mnecas** [comment] 2020-10-03 19:14
Yeah, this is in all _info modules so we have it in an external fragment.
Happy that it helped.
Closing: RESOLVED

**Closed by mnecas** 2020-10-03 19:14 UTC
Labels: bug
