### ISSUE TITLE
Ovirt_disks : cannot rename disk

### ISSUE THREAD

**Issue by sflotron** [oVirt/ovirt-ansible-collection#362] opened 2021-10-18 08:24 UTC
##### SUMMARY

Since upgrading to version >= 1.6.0, we cannot rename disk

##### COMPONENT NAME

ovirt.ovirt.ovirt_disk

##### STEPS TO REPRODUCE

Call this ansible block 
```yaml
  - name: Rename OS disk
    ovirt.ovirt.ovirt_disk:
      auth: "{{ ovirt_auth }}"
      id: "{{ result_vm_after.ovirt_vms[0]['disk_attachments'][0]['id'] }}"
      storage_domain: "{{ datastore_cluster }}"
      name: "{{ inventory_hostname }}_os"
      vm_name: "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS
The OS disk is renamed

##### ACTUAL RESULTS

The ansible instruction throw the following error

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "Updating disk attributes other than QCOW version is permitted only for disk-attachments, which reside under VMs.". HTTP response code is 409
```

**Comment by mnecas** [comment] 2021-10-18 08:30
Thanks for the issue will check it out!

**Comment by mnecas** [comment] 2021-11-12 09:30
@barpavel any updates on the issue?

**Comment by barpavel** [comment] 2021-11-15 14:53
> @barpavel any updates on the issue?

Currently there is no progress with this and other similar pending issues.
Until 4.5.0 release we do not have capacity for it :(
If any plan of priorities is needed, @shenitzky should be contacted.

**Comment by stesnape** [comment] 2022-11-09 14:07
Hi 

Has this been progressed ? I'm running v4.5.1 and still have this issue with not being able to rename a disk with the exact same output/error as above

**Comment by Gounick** [comment] 2022-11-29 15:34
I have the same problem with the same error message.

After creating a VM from a template, the disk retains the same name present in the template. I'm looking to rename it to the same name of the VM + index.

I tried to rename the disk but only failures:
* :x: COW disk (attached)
* :x: RAW disk (attached)
* :x: COW disk (detached)
* :x: RAW disk (detached)

My versions:
* ovirt engine 4.3
* ovirt.ovirt collection latest from https://galaxy.ansible.com/ (=2.4.0 today)
* ovirt-engine-sdk-python = "==4.5.*"
* ansible-core = "==2.12.*"
* python_version = "3.8"

**Comment by Gounick** [comment] 2022-12-01 12:35
Hi,
I reread the API documentation in detail and I think I have found my solution: update the oVirt Engine to >= 4.4

In oVirt Engine v4.3, it is not possible to rename an existing disk:
* https://ovirt.github.io/ovirt-engine-api-model/4.3/#services/disk/methods/update

This is only possible from oVirt Engine v4.4:
* https://ovirt.github.io/ovirt-engine-api-model/4.4/#services/disk/methods/update
* https://ovirt.github.io/ovirt-engine-api-model/4.5/#services/disk/methods/update
* https://ovirt.github.io/ovirt-engine-api-model/master/#services/disk/methods/update

**Comment by mwperina** [comment] 2022-12-05 08:53
Based on above closing as not a bug

**Closed by mwperina** 2022-12-05 08:53 UTC
Labels: bug
